spring:
  datasource:
    url: jdbc:mysql://116.62.155.169:3306/seat_dev?useUnicode=true&characterEncoding=UTF-8
    username: kevin
    password: WEIya@135
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    cors:
      allowed-origins: http://localhost:5173
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true



